image: docker:latest

variables:
  REPOSITORY_URL: rizkirifani7/task-5
  IMAGE_TAG: latest

services:
  - docker:dind

before_script:
  - docker login --username=$DH_USERNAME --password=$DH_PASSWORD

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build
      -t task-5:latest
      --build-arg PORT=$PORT
      --no-cache .
    - echo "Tagging image..."
    - docker tag task-5:latest $REPOSITORY_URL:latest
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker stop task-5 || true && docker rm task-5 || true
    - docker container run -dt -p $PORT:$PORT --name task-5 $REPOSITORY_URL:latest
    - docker image prune -f
  only:
    - main
